name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID: continuous-deployment
  RUN_REGION: us-east1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'to deploy')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA"
          gcloud builds submit --tag $IMAGE_TAG
          echo "::set-env name=IMAGE_TAG::$IMAGE_TAG"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $APP_ID \
            --image $IMAGE_TAG \
            --platform managed \
            --region $RUN_REGION \
            --allow-unauthenticated
