name: Continuous Deployment to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          app_id: ${{ secrets.GCP_APP_ID }}
          export_default_credentials: true

      - name: Authenticate Docker to GCR
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/project_id/app_id:${{ github.sha }} .
          docker push gcr.io/project_id/app_id:${{ github.sha }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy app_id \
            --image gcr.io/project_id/app_id:${{ github.sha }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated